# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Thomas algorithm for solving tridiagonal linear systems. Stability only for diagonally dominant or symmetric positive definite.
#'
#' @param a lower diagonal of matrix
#' @param b diagonal of matrix
#' @param c upper diagonal of matrix
#' @param d vector on RHS of equation
#'
#' @description {Thomas algorithm for tridiagonal linear systems. This can be used to solve
#' PDEs arising from Feynman-Kac connections.}
#' @details {The algorithm is on wikipedia and quite straightforward.}
#' @export thomas_algorithm
thomas_algorithm <- function(a, b, c, d) {
    .Call(`_numerics_thomas_algorithm`, a, b, c, d)
}

